secrets:
  version: 1.0.0
  output: ./.x82-secrets.env
  jobs:
    - name: deploy.nodejsModule.opensource
      values: 
        - engine: kv-v2
          path: ops/prod/npm
          aliases: 
            - field: token
              name: NPM_TOKEN